// app_react/resources/js/rota/App.jsx
import React from "react";
import {
  BrowserRouter,
  Switch,
  Route,
  Link
} from "react-router-dom";

import { Home } from './pages/Home/index.jsx'
import { About } from './pages/About/index.jsx'

export function App() {
  return (
    <BrowserRouter>
      <div>
        <ul>
          <li>
            <Link to="/router">Home</Link>
          </li>
          <li>
            <Link to="/router/about">About</Link>
          </li>
        </ul>

        <hr />

        <Switch>
          <Route exact path="/router">
            <Home />
          </Route>
          <Route path="/router/about">
            <About />
          </Route>
        </Switch>
      </div>
    </BrowserRouter>
  );
}

// app_vue/resources/js/rota/App.vue
<template>
  <div>
    <ul>
      <li>
        <router-link :to="{ name: 'home'}">Home</router-link>
      </li>
      <li>
        <router-link :to="{ name: 'about'}">About</router-link>
      </li>
    </ul>

    <hr />

    <router-view></router-view>
  </div>
</template>

<script>
export default {
}
</script>
